export enum Events {
    ContentUpdate = "onContentChange",
    ViewportChange = "onViewportChange",
    MouseUp = "mouseup",
    MouseDown = "mousedown",
    MouseEnter = "mouseenter",
    MouseLeave = "mouseleave",
    MouseMove = "mousemove",
    Click = "click",
    Scroll = "scroll",
    KeyUp = "keyup",
    KeyDown = "keydown",
    Focus = "focus",
    Blur = "blur",
    DragEnter = "dragenter",
    DragStart = "dragstart",
    DragOver = "dragover",
    DragLeave = "dragleave",
    Drop = "drop",
    DragEnd = "dragend",
    Paste = "paste",
    Error = "error",
    UnhandledRejection = "unhandledrejection",
    Undo = "onUndo",
    Redo = "onRedo",
    PopupRequest = "onPopupRequest",
    PopupRepositionRequest = "onPopupRepositionRequest"
}
